# Generated by Django 6.1.1 on 2026-09-27 09:52

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('opendatasoft', 'API Opendatasoft (data.gouv.nc)'), ('rest', 'API REST JSON'), ('csv', 'Fichier CSV (adresse ou document déposé)')], default='opendatasoft', max_length=20)),
                ('url_base', models.URLField(help_text="Opendatasoft : https://data.gouv.nc ; REST : adresse complète de l'API ; CSV : adresse du fichier", verbose_name='adresse')),
                ('jeu', models.CharField(blank=True, help_text='Opendatasoft uniquement, par exemple sempex_prix_medicaments_en_vigueur', max_length=200, verbose_name='identifiant du jeu de données')),
                ('chemin_liste', models.CharField(blank=True, help_text='Clés séparées par des points menant à la liste de lignes, ex. data.items', max_length=200, verbose_name='chemin de la liste (REST)')),
                ('cle', models.CharField(blank=True, help_text="Champ unique d'une ligne ; sert aux alertes « nouvelle ligne ». Vide : empreinte de la ligne.", max_length=100, verbose_name='champ identifiant')),
                ('max_lignes', models.PositiveIntegerField(default=5000)),
                ('frequence_heures', models.PositiveIntegerField(default=24, verbose_name='fréquence de lecture (heures)')),
                ('licence', models.CharField(blank=True, default='Licence ouverte', max_length=200)),
                ('champs', models.JSONField(blank=True, default=list, editable=False)),
                ('derniere_lecture', models.DateTimeField(blank=True, editable=False, null=True)),
                ('derniere_erreur', models.TextField(blank=True, editable=False)),
                ('nb_lignes', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'source de données',
                'verbose_name_plural': 'sources de données',
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveIntegerField()),
                ('identifiant', models.CharField(db_index=True, max_length=200)),
                ('donnees', models.JSONField()),
                ('texte', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='tableaux.sourcedonnees')),
            ],
            options={
                'ordering': ['rang'],
                'indexes': [models.Index(fields=['source', 'rang'], name='tableaux_li_source__a60ebb_idx')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('filtre', models.CharField(blank=True, help_text='Mot à trouver dans la ligne ; vide = toutes', max_length=200)),
                ('jeton', models.CharField(editable=False, max_length=40, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='tableaux.sourcedonnees')),
            ],
            options={
                'unique_together': {('source', 'email', 'filtre')},
            },
        ),
    ]
