# Generated by Django 6.1.1 on 2026-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedonnees',
            name='filtre',
            field=models.CharField(blank=True, help_text='Clause ODSQL « where », ex. prix_cfp is not null', max_length=300, verbose_name='filtre à la lecture (Opendatasoft)'),
        ),
    ]
