# Generated by Django 6.1.1 on 2026-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaux', '0002_sourcedonnees_filtre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcedonnees',
            name='champ_geo',
            field=models.CharField(blank=True, help_text='Pour la carte : champ point {lon, lat} (ex. geo_point_2d) ou deux champs « latitude,longitude »', max_length=120, verbose_name='champ de localisation'),
        ),
        migrations.AddField(
            model_name='sourcedonnees',
            name='champs_conserves',
            field=models.CharField(blank=True, help_text='Minimisation (RGPD) : liste des champs gardés, séparés par des virgules ; les autres ne sont ni stockés ni indexés. Vide : tous.', max_length=500, verbose_name='champs conservés'),
        ),
    ]
