# Generated by Django 6.1.1 on 2026-09-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaux', '0003_ligne_lat_ligne_lon_sourcedonnees_champ_geo_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedonnees',
            name='document',
            field=models.ForeignKey(blank=True, help_text="CSV : fichier déposé dans la médiathèque (prioritaire sur l'adresse)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='sourcedonnees',
            name='url_base',
            field=models.URLField(blank=True, help_text="Opendatasoft : https://data.gouv.nc ; REST : adresse complète de l'API ; CSV : adresse du fichier", verbose_name='adresse'),
        ),
    ]
