# Generated by Django 6.1.1 on 2026-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaux', '0004_sourcedonnees_document_alter_sourcedonnees_url_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedonnees',
            name='correspondance_schema',
            field=models.CharField(blank=True, help_text='propriété=champ, séparés par des virgules, ex. title=poste,hiringOrganization=employeur,validThrough=cloture', max_length=400, verbose_name='correspondance des champs'),
        ),
        migrations.AddField(
            model_name='sourcedonnees',
            name='schema_ligne',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('JobPosting', "Offre d'emploi (JobPosting)")], default='', help_text='Type schema.org publié sur chaque fiche (moteurs de recherche, assistants IA)', max_length=40, verbose_name='données structurées de la fiche'),
        ),
        migrations.AlterField(
            model_name='sourcedonnees',
            name='chemin_liste',
            field=models.CharField(blank=True, help_text='REST : clés séparées par des points menant à la liste, ex. data.items. Page web : lien de chaque ligne, avec ses attributs data-, ex. /avis/download/{pdf}', max_length=200, verbose_name='chemin de la liste (REST) ou modèle de lien (page web)'),
        ),
        migrations.AlterField(
            model_name='sourcedonnees',
            name='type',
            field=models.CharField(choices=[('opendatasoft', 'API Opendatasoft (data.gouv.nc)'), ('rest', 'API REST JSON'), ('csv', 'Fichier CSV (adresse ou document déposé)'), ('page_html', "Tableaux d'une page web (connecteur transitoire)")], default='opendatasoft', max_length=20),
        ),
    ]
