# Generated by Django 6.1.1 on 2026-09-27 09:52

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContenu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('chapo', models.TextField(blank=True, help_text="Réponse courte à la question de l'usager ; reprise par les moteurs", verbose_name='chapô')),
                ('gabarit', models.CharField(choices=[('standard', 'Standard (colonne de lecture)'), ('large', 'Large (tableaux, données)'), ('accueil', 'Accueil de site (chapô et rubriques)')], default='standard', max_length=20)),
                ('corps', wagtail.fields.StreamField([('alerte', 2), ('intertitre', 3), ('paragraphe', 4), ('encadre', 6), ('tableau', 17)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Information'), ('attention', 'Attention')]}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link']}), 2: ('wagtail.blocks.StructBlock', [[('niveau', 0), ('message', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Titre de section', 'template': 'home/blocs/intertitre.html'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'icon': 'pilcrow', 'label': 'Paragraphe'}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('titre', 5), ('texte', 1)]], {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('tableaux.SourceDonnees',), {}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Nom du champ de la source (voir « État de la source »)'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Intitulé affiché ; vide = nom du champ', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('champ', 9), ('libelle', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Colonnes de la liste', 'min_num': 1}), 13: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Vide : tous les champs de la ligne', 'label': 'Champs de la fiche détail', 'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Champ de recherche', 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 25, 'label': 'Lignes par page', 'max_value': 200, 'min_value': 5}), 16: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': "Proposer l'alerte e-mail", 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('source', 7), ('titre', 8), ('colonnes', 12), ('colonnes_detail', 13), ('recherche', 14), ('par_page', 15), ('abonnement', 16)]], {})})),
            ],
            options={
                'verbose_name': 'page de contenu',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('pagecontenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.pagecontenu')),
            ],
            options={
                'verbose_name': 'accueil de site',
            },
            bases=('home.pagecontenu',),
        ),
    ]
