# Generated by Django 6.1.1 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontenu',
            name='pictogramme',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('douane', 'Douane et commerce'), ('sante', 'Santé'), ('emploi', 'Emploi et concours'), ('actualites', 'Actualités'), ('donnees', 'Textes et données')], default='', help_text="Pictogramme affiché sur la tuile de la rubrique, à l'accueil", max_length=20),
        ),
    ]
