# Generated by Django 6.1.1 on 2026-09-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pagecontenu_corps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontenu',
            name='pictogramme',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('douane', 'Douane et commerce'), ('sante', 'Santé'), ('emploi', 'Emploi et concours'), ('actualites', 'Actualités'), ('donnees', 'Textes et données'), ('mobilite', 'Mobilité'), ('artisanat', 'Artisanat et entreprises')], default='', help_text="Pictogramme affiché sur la tuile de la rubrique, à l'accueil", max_length=20),
        ),
    ]
