# Generated by Django 6.1.1 on 2026-09-27 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienMort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('statut', models.CharField(help_text='Code HTTP ou erreur réseau', max_length=40)),
                ('vu_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'lien mort',
                'verbose_name_plural': 'liens morts',
                'ordering': ['page__title', 'url'],
            },
        ),
        migrations.CreateModel(
            name='PageVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(db_index=True)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'unique_together': {('page', 'jour')},
            },
        ),
    ]
